# Theme Configuration
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.svg
  favicon: assets/favicon.png

# Site Settings
site_name: R-Type Documentation
site_description: Documentation for the R-Type game engine
site_url: https://lucas99913.github.io/Doc-RType
repo_url: https://github.com/Lucas99913/Doc-RType
repo_name: Lucas99913/Doc-RType

# Markdown Processing
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true

# File Handling
include:
  - LICENSE
  - "*.md"
  - "*.markdown"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .gitignore
  - README.md
  - CONTRIBUTING.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extra Settings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lucas99913/Doc-RType
  version:
    provider: mike