# Theme Configuration
theme: jekyll-theme-minimal
title: R-Type Documentation
description: Documentation for the R-Type game engine

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  hard_wrap: false
  mermaid:
    theme: dark

# Syntax Highlighting
highlighter: rouge

# Plugins
plugins:
  - jekyll-mermaid

# Build Configuration
livereload: true
incremental: false
mermaid:
  version: "9.1.7"

# File Handling
include:
  - LICENSE
  - "*.md"
  - "*.markdown"
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .gitignore
  - README.md
  - CONTRIBUTING.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      mermaid: true
  - scope:
      path: "docs"
      type: "docs"
    values:
      layout: "doc"
      mermaid: true