# Theme Configuration
remote_theme: pages-themes/cayman@v0.2.0
title: R-Type Documentation
description: Documentation for the R-Type game engine

# Markdown Processing
markdown: GFM
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  toc_levels: 1..3

# Syntax Highlighting
highlighter: rouge

# File Handling
include:
  - LICENSE
  - "*.md"
  - "*.markdown"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .gitignore
  - README.md
  - CONTRIBUTING.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "docs"
    values:
      layout: "doc"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Theme Options
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/Lucas99913/Doc-RType
  owner_url: https://github.com/Lucas99913
  owner_name: Lucas99913

# Custom Styling
colors:
  header: "#6B46C1"              # Violet principal
  gradient_left: "#4834D4"       # Bleu indigo foncé
  gradient_right: "#8B5CF6"      # Violet plus clair
  link: "#4C1D95"                # Violet foncé pour les liens
  section_headings: "#5B21B6"    # Violet moyen pour les titres de sections