# Theme Configuration
remote_theme: pages-themes/cayman@v0.2.0
title: R-Type Documentation
description: Documentation for the R-Type project

# Markdown Processing
markdown: GFM
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  toc_levels: 1..3

# Syntax Highlighting
highlighter: rouge

# File Handling
include:
  - LICENSE
  - "*.md"
  - "*.markdown"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .gitignore
  - README.md
  - CONTRIBUTING.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "docs"
    values:
      layout: "doc"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Theme Options
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/theo-wq/B-CPP-500-MAR-5-2-rtype-theo.berget
  owner_url: https://github.com/theo-wq
  owner_name: theo-wq
  zip_url: https://github.com/theo-wq/B-CPP-500-MAR-5-2-rtype-theo.berget/zipball/main
  tar_url: https://github.com/theo-wq/B-CPP-500-MAR-5-2-rtype-theo.berget/tarball/main

# Custom Styling
colors:
  header: "#6B46C1"
  gradient_left: "#4834D4"
  gradient_right: "#8B5CF6"
  link: "#4C1D95"
  section_headings: "#5B21B6"