# Theme Configuration
theme: jekyll-theme-minimal
title: R-Type Documentation
description: Documentation for the R-Type game engine

# Markdown Processing
markdown: GFM
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Syntax Highlighting
highlighter: rouge

# File Handling
include:
  - LICENSE
  - "*.md"
  - "*.markdown"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .gitignore
  - README.md
  - CONTRIBUTING.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "docs"
    values:
      layout: "doc"