theme: jekyll-theme-minimal
title: R-Type Documentation
description: Documentation for the R-Type game engine
markdown: GFM
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
highlighter: rouge
mermaid:
  version: "10.6.1"
plugins:
  - jekyll-mermaid
defaults:
  - scope:
      path: ""
    values:
      mermaid: true
include: 
  - "LICENSE"
  - "_*.html"
  - "*.md"
exclude:
  - ".gitignore"
  - "Gemfile"
  - "Gemfile.lock"