# Theme Configuration
remote_theme: just-the-docs/just-the-docs
title: R-Type Documentation
description: Documentation for the R-Type game engine

# Markdown Processing
markdown: GFM
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Theme Settings
color_scheme: dark
search_enabled: true
heading_anchors: true

# File Handling
include:
  - LICENSE
  - "*.md"
  - "*.markdown"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .gitignore
  - README.md
  - CONTRIBUTING.md

# Just the Docs Settings
aux_links:
  "View on GitHub":
    - "https://github.com/Lucas99913/Doc-RType"
aux_links_new_tab: true

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/EpitechPromo2027/B-CPP-500-MAR-5-2-rtype-theo.berget
    hide_icon: false

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "docs"
    values:
      layout: "doc"

# Footer Settings
footer_content: "Copyright &copy; 2024 R-Type Documentation. Distributed under MIT license."